name: asset_helper
description: Example project for asset_helper

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  asset_helper:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
# Asset Helper configuration
asset_helper:
  output_dir: lib/generated
  asset_class_name: Assets
  include_comments: true
  use_new_naming_convention: true 